export interface ApiResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
}
export interface User {
  id: string;
  name: string;
  role: 'admin' | 'pharmacist' | 'viewer';
}
export interface Category {
  id: string;
  name: string;
  description?: string;
}
export interface Supplier {
  id: string;
  name: string;
  contactPerson: string;
  email: string;
  phone: string;
  address: string;
}
export interface Customer {
  id: string;
  name: string;
  email: string;
  phone: string;
  address?: string;
  creditLimit: number;
  currentBalance: number;
}
export interface Product {
  id: string;
  name: string;
  tradeName?: string;
  scientificName?: string;
  barcode?: string;
  sku: string;
  categoryId: string;
  supplierId: string;
  price: number;
  costPrice: number;
  taxRate: number;
  discountRate: number;
  stockQuantity: number;
  unit: string;
  expiryDate: string;
  batchNumber: string;
  minStockLevel: number;
}
export interface SaleItem {
  productId: string;
  quantity: number;
  unitPrice: number;
  taxAmount: number;
  discountAmount: number;
  subtotal: number;
}
export interface Transaction {
  id: string;
  invoiceNumber?: string;
  customerId?: string;
  userId: string;
  items: SaleItem[];
  subtotal: number;
  taxTotal: number;
  discountTotal: number;
  totalAmount: number;
  paymentMethod: 'cash' | 'card' | 'transfer';
  status: 'completed' | 'pending' | 'cancelled';
  timestamp: number;
  metadata?: {
    isAutoGenerated: boolean;
  };
}
export interface PurchaseItem {
  productId: string;
  quantity: number;
  costPrice: number;
}
export interface PurchaseOrder {
  id: string;
  invoiceNumber?: string;
  supplierId: string;
  items: PurchaseItem[];
  totalCost: number;
  status: 'pending' | 'received' | 'cancelled';
  timestamp: number;
}
// Accounting Entities
export type AccountType = 'asset' | 'liability' | 'equity' | 'revenue' | 'expense';
export interface Account {
  id: string;
  name: string;
  code: string;
  type: AccountType;
  balance: number;
  description?: string;
}
export interface JournalEntryItem {
  accountId: string;
  debit: number;
  credit: number;
}
export interface JournalEntry {
  id: string;
  date: number;
  description: string;
  referenceId: string;
  items: JournalEntryItem[];
}
export interface Expense {
  id: string;
  date: number;
  accountId: string;
  paymentAccountId: string;
  amount: number;
  category: string;
  description: string;
  status: 'paid' | 'pending';
}
export interface Alert {
  id: string;
  type: 'expiry' | 'stock' | 'credit' | 'system';
  productId: string;
  message: string;
  severity: 'low' | 'medium' | 'high';
  status: 'active' | 'resolved';
  timestamp: number;
}
// Subscription Types
export type BillingCycle = 'monthly' | 'yearly';
export type SubscriptionPlanId = 'starter' | 'pro' | 'enterprise';
export type SubscriptionStatus = 'active' | 'past_due' | 'cancelled';
export interface SubscriptionInfo {
  planId: SubscriptionPlanId;
  status: SubscriptionStatus;
  billingCycle: BillingCycle;
  nextBillingDate: string;
}
export interface BillingRecord {
  id: string;
  date: string;
  amount: number;
  planId: SubscriptionPlanId;
  invoiceUrl: string;
  status: 'paid' | 'pending';
}
export interface DashboardStats {
  totalSales: number;
  totalOrders: number;
  lowStockItems: number;
  expiredSoonCount: number;
  recentSales: Transaction[];
}
export interface AnalyticsReport {
  inventoryValue: number;
  revenueByDay: { date: string; amount: number }[];
  categoryDistribution: { category: string; count: number; value: number }[];
  profitSummary: { revenue: number; cost: number; profit: number };
}